-- add bu touxin 增加预警规则表
DROP TABLE "KV_DS_WRINING_RULE";
CREATE TABLE "KV_DS_WRINING_RULE" (
"ID" VARCHAR2(32 BYTE) NOT NULL ,
"NAME" VARCHAR2(32 BYTE) NULL ,
"VEHICLE_TYPE" VARCHAR2(32 BYTE) NULL ,
"RULE_TYPE" VARCHAR2(32 BYTE) NULL ,
"RULE" CLOB NULL ,
"CREATE_TIME" DATE NULL ,
"UPDATE_TIME" DATE NULL
)
LOGGING
NOCOMPRESS
NOCACHE;

COMMENT ON TABLE "KV_DS_WRINING_RULE" IS '预警规则';
COMMENT ON COLUMN "KV_DS_WRINING_RULE"."VEHICLE_TYPE" IS '车辆类型';
COMMENT ON COLUMN "KV_DS_WRINING_RULE"."RULE_TYPE" IS '规则类型';
COMMENT ON COLUMN "KV_DS_WRINING_RULE"."RULE" IS '规则详细';

ALTER TABLE "KV_DS_WRINING_RULE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "KV_DS_WRINING_RULE" ADD CHECK ("ID" IS NOT NULL);

ALTER TABLE "KV_DS_WRINING_RULE" ADD PRIMARY KEY ("ID");

